name: Run build & tests

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
                pnpm-version: [9]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: ${{ matrix.pnpm-version }}

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build project
              run: pnpm build

            - name: Run tests
              run: pnpm test
