name: Publish

on:
    release:
        types: [published]

jobs:
    build:
        name: Publish
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
                pnpm-version: [9]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: ${{ matrix.pnpm-version }}

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Run tests
              run: pnpm test

            - name: Build project
              run: pnpm build

            - name: Publish to npm
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  npm publish
